name       : knewstuff
version    : 5.35.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.35/knewstuff-5.35.0.tar.xz : a8bf7bd0d4a954b0dcdbd52ffdc09125cd47c02af42e350dbc7101d2c997f5f6
license    : LGPL-2.1
component  : programming
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKF5Attica)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
