name       : knewstuff
version    : 5.99.0
release    : 73
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.99/knewstuff-5.99.0.tar.xz : 4824b6aa08c58671b182ba489d45a83122b522315750cc90cf8f544337d4a72d
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : programming.library
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - attica-devel
    - karchive-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
    - ktextwidgets-devel
    - sonnet-devel
    - syndication-devel
rundeps    :
    - devel :
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
