name       : knewstuff
version    : 5.62.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/knewstuff-5.62.0.tar.xz : 5ec7806bf1c5d24a0f393fc48950afefc4bbd1b04b2ad1db59f5f05ecd8f0195
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
builddeps  :
    - pkgconfig(libKF5Attica)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
