name       : knewstuff
version    : 5.57.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/knewstuff-5.57.0.tar.xz : 6a9d77a62b036b4ed0f32ffaa9f204db1403030d01dbe8fb055d02361db2f981
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
builddeps  :
    - pkgconfig(libKF5Attica)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
