name       : knewstuff
version    : 5.28.0
release    : 4
source     :
    - http://download.kde.org/stable/frameworks/5.28/knewstuff-5.28.0.tar.xz : 4363f472508d9abc39a5707a2b38a9c0cf79bc7c11030a6a8cd03a9cef37aa5c
license    : LGPL-2.1
component  : programming
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKF5Attica)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel:
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
