name       : knewstuff
version    : 5.92.0
release    : 68
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.92/knewstuff-5.92.0.tar.xz : 4b14aee55d7701c72d05030fad508a5cb89fee34656d4d84c2d977a3c2a66c3f
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : programming.library
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - attica-devel
    - karchive-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
    - ktextwidgets-devel
    - sonnet-devel
    - syndication-devel
rundeps    :
    - devel :
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %patch -p1 -i $pkgfiles/fix-user-visible.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
