name       : knewstuff
version    : 5.80.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/knewstuff-5.80.0.tar.xz : dfe874f7fe944fe877c0d443349102ceacb268c45dc1f666ec42ff219024735d
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : programming.library
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - attica-devel
    - karchive-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
    - ktextwidgets-devel
    - sonnet-devel
rundeps    :
    - devel :
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
