name       : knewstuff
version    : 5.50.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/knewstuff-5.50.0.tar.xz : 0df2264795d5ea017fc64d236ab28ea353c6c1466655da76ae179a022804b0c6
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
builddeps  :
    - pkgconfig(libKF5Attica)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kitemviews-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
