name       : knewstuff
version    : 5.44.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/knewstuff-5.44.0.tar.xz : 0ad4a773933c8de34b27c0e444d40eace012251aadb6f112a32df6fb003aa5e9
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKF5Attica)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kitemviews-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
