name       : knewstuff
version    : 5.64.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/knewstuff-5.64.0.tar.xz : 91334c95a1082ae402ee869da399e5bdbac986c8b30a85d0a899b30de1f3be72
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
builddeps  :
    - pkgconfig(libKF5Attica)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
