name       : knewstuff
version    : 5.79.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/knewstuff-5.79.0.tar.xz : 3e2055002f7e2f8cbffb414b7cd98ed38b911b95d5eee914139389a041064f2f
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : programming.library
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - attica-devel
    - karchive-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
    - ktextwidgets-devel
    - sonnet-devel
rundeps    :
    - devel :
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
