name       : knewstuff
version    : 5.43.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/knewstuff-5.43.0.tar.xz : 879f8ea4b4a920523d6cb58c4391a46251d83974bfdb25ac4a0bcb109bff7cec
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKF5Attica)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kitemviews-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
