name       : knewstuff
version    : 5.53.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/knewstuff-5.53.0.tar.xz : 039b38e8599cb1320c1c8cc8452c9ac9b24e864bca49507295184967dcd7be34
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
builddeps  :
    - pkgconfig(libKF5Attica)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kitemviews-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
