name       : knewstuff
version    : 5.78.0
release    : 51
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/knewstuff-5.78.0.tar.xz : d5b0abd5d4ff67e1f4fb921b710d1251569bfc2e19788d9ce7843b498f9a61b9
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : programming.library
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - attica-devel
    - karchive-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
    - ktextwidgets-devel
    - sonnet-devel
rundeps    :
    - devel :
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
