name       : knewstuff
version    : 5.25.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.25/knewstuff-5.25.0.tar.xz : a1a3c5b096e24afd40284256449f797e1656663a91d175a2ad3cd4aa6bfd9ca8
license    : LGPL-2.1
component  : programming
summary    : Framework for downloading and sharing additional application data.
description: |
    Framework for downloading and sharing additional application data.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKF5Attica)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel:
        - attica-devel
        - kservice-devel
        - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
